### ISSUE TITLE
[Android] Zoom Video Call UI is breaking on landscape rotation on  some android devices (specially on Android version 12)

### ISSUE THREAD

**Issue by kamaljitSharma** [mieszko4/react-native-zoom-us#228] opened 2022-08-08 11:21 UTC
Hi
react-native-zoom-us: 6.13.0
react-native: 0.68.2

I am facing the UI distortion issue for some android devices on a zoom video call

When I change the orientation from Portrait to Landscape mode, the video becomes too big and doesn't fit on the screen. This issue is occurring on Samsung Galaxy M32 (Android OS version - 12 )

**Comment by kamaljitSharma** [comment] 2022-08-09 12:24
it looks issue is on Android version 12, once we rotate the device to landscape the zoom meeting screen UI looks distorted

**Comment by link692-dev** [comment] 2022-08-11 06:42
Hello
I am facing the same issue.

- Zoom Meeting Screen launches with portrait layout, it does not change into landscape layout by rotation.
- Zoom Meeting Screen launches with landscape layout, it changes well by rotation.

device : google pixel 6
android os version : 12
react-native: 0.68.2
react-native-zoom-us: 6.6.1

**Comment by kamaljitSharma** [comment] 2022-09-05 07:02
@mieszko4 can you suggest any possible solution for this issue?

**Comment by mieszko4** [comment] 2022-09-14 17:59
We should upgrade Zoom SDK for Android to the newest version. I tried to do that already but there were some conflicts with react-native (https://github.com/mieszko4/react-native-zoom-us/pull/219). 
Perhaps with newest Zoom SDK there won't be issues anymore (https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-10)

**Comment by sabishm** [comment] 2022-11-03 15:43
@mieszko4 Any update about this issue?

**Comment by murtazakaz** [comment] 2022-11-09 17:56
Hey @mieszko4, any update on this issue? We need to resolve this asap. 
Let me know If I can help you with that.

**Comment by bshubham80** [comment] 2023-02-10 08:45
@mieszko4 Any update about this issue?

**Comment by mieszko4** [comment] 2023-02-14 07:05
The newest lib 6.16.5 uses Zoom SDK 5.13.1 but there is still this issue showing up.

It looks like it is an issue of Zoom SDK so we do not have control over it.
I suggest confirming if the issue is in their newest Zoom SDK Android example. If yes, then reporting this issue on [their forum.
](https://devforum.zoom.us/)
Alternatively, can can use [enableCustomizedMeetingUI](https://github.com/mieszko4/react-native-zoom-us/blob/master/docs/VIDEO-VIEW.md)  (Android only) and set up UI elements yourself.

**Comment by rahulvyas** [comment] 2023-02-18 15:01
> Hey @mieszko4, any update on this issue? We need to resolve this asap. Let me know If I can help you with that.

Were you able to resolve this issue?
I'm also facing this issue in android devices

**Comment by bshubham80** [comment] 2023-02-20 06:32
Hey @rahulvyas, You can start joining in landscape mode initially will keep this bug for you. I have checked and working fine

**Comment by rahulvyas** [comment] 2023-02-21 06:34
> Hey @rahulvyas, You can start joining in landscape mode initially will keep this bug for you. I have checked and working fine

You mean users have to start meeting initially in landscape mode

**Comment by bshubham80** [comment] 2023-02-21 06:38
Yes,

**Comment by sabishm** [comment] 2023-02-23 06:44
I fixed my self.

**Comment by mieszko4** [comment] 2023-02-23 07:20
@sabishm What did you do to fix it?

**Comment by viettranbhtech** [comment] 2023-02-28 04:20
Any update to resolve this issue?

**Comment by murtazakaz** [comment] 2023-03-30 20:42
> I fixed my self.

@sabishm how? kindly share us the solution

**Comment by sabishm** [comment] 2023-05-08 02:55
Using latest zoom SDK.

**Comment by mieszko4** [comment] 2023-07-10 09:06
Ok, This should be closed by https://github.com/mieszko4/react-native-zoom-us/issues/280 then.

**Comment by ajayhcode** [comment] 2023-07-28 06:36
This issue is still persisted

**Comment by mieszko4** [comment] 2023-07-28 22:30
Try with 6.18.0 - it uses Android ZoomSDK 5.13.10.

**Comment by mieszko4** [comment] 2023-07-28 22:44
I see that if I start meeting in portrait mode and do rotation then it works. However bottom buttons do not show up so there is still an issue but that seems to be an issue of native Android Zoom SDK.

**Comment by ajayhcode** [comment] 2023-07-31 10:04
> Try with 6.18.0 - it uses Android ZoomSDK 5.13.10.

The issue is also persist with new update too. Even on android 13 also

**Comment by mieszko4** [comment] 2024-01-21 23:26
Please try with react-native-zoom-us@6.20.0 which uses updated ZoomSDK to 5.16.2.16555). I tested it on Android 13 and it works well now.

**Closed by mieszko4** 2024-01-21 23:26 UTC
