### ISSUE TITLE
Minimize Meeting

### ISSUE THREAD

**Issue by ds4u-sanjeev** [mieszko4/react-native-zoom-us#203] opened 2022-04-28 05:19 UTC
I am using this SDK with latest version 6.8.1 but I didn't found option of "Minimise Meeting" inside more "...". This option available in zoom application while we are using in the android mobile phone. So please help to enable this option.

**Comment by mieszko4** [comment] 2022-09-14 17:56
Duplicate of https://github.com/mieszko4/react-native-zoom-us/issues/223

**Closed by mieszko4** 2022-09-14 17:56 UTC
Labels: enhancement
