### ISSUE TITLE
Join meeting crashes the app in android 12 and above devices 

### ISSUE THREAD

**Issue by ajayhcode** [mieszko4/react-native-zoom-us#282] opened 2023-07-11 07:15 UTC
# Join meeting crashes the app in android 12 and above devices  but working fine in below devices. 
## This is happening in  example app provided too.

I am able to initialise the sdk. But as soon as i click on Join meeting from example app. The app crashes.
I have attached android studio error logs kindly reply asap.
#[error.txt](https://github.com/mieszko4/react-native-zoom-us/files/12011870/error.txt)

@jcamins  @mialy  @hans00  @mieszko4 Kindly look into this and suggest.

**Comment by chirag-codealchemy** [comment] 2023-07-11 12:12
Please try to upgrade React native version if possible, because I faced a similar error in past and I  solved it by upgrading React native version  

Note:- Please provide more details (react native version, minimal repo to reproduce the error)

**Comment by ajayhcode** [comment] 2023-07-11 12:18
i am using the example app provided

**Comment by ajayhcode** [comment] 2023-07-11 12:18
The example app should be workable

**Comment by ajayhcode** [comment] 2023-07-13 10:08
Hello is there any fix for this or any working fork .

**Comment by mieszko4** [comment] 2023-07-20 08:13
Should be fixed by upgrading react (https://github.com/mieszko4/react-native-zoom-us-test/issues/70) but i did not find time to do that yet.

**Comment by mieszko4** [comment] 2023-07-24 08:23
Closing since https://github.com/mieszko4/react-native-zoom-us-test/issues/70 is implemented now.

**Closed by mieszko4** 2023-07-24 08:23 UTC
