### ISSUE TITLE
[Android] Crashing on some devices

### ISSUE THREAD

**Issue by bhavesh0206s** [mieszko4/react-native-zoom-us#187] opened 2022-01-31 10:59 UTC
Dependencies:
```
"react": "17.0.1",
"react-native": "0.64.1",
"react-native-zoom-us": "^6.6.1",
```

Error Logs:
```
com.zipow.videobox.mainboard.Mainboard.getMainboard (Mainboard.java)
com.zipow.cmmlib.ZoomAppPropData.getInstance (ZoomAppPropData.java)
com.zipow.cmmlib.AppContext$AppContextImpl.getTimestamp (AppContext.java)
com.zipow.cmmlib.AppContext$AppContextImpl.loadProperties (AppContext.java)
com.zipow.cmmlib.AppContext$AppContextImpl.queryWithKey (AppContext.java)
com.zipow.cmmlib.AppContext.queryWithKey (AppContext.java)
com.zipow.videobox.mainboard.Mainboard.initMainboard (Mainboard.java)
com.zipow.videobox.mainboard.Mainboard.initialize (Mainboard.java)
com.zipow.videobox.VideoBoxApplication.initSDKMainboard (VideoBoxApplication.java)
com.zipow.videobox.VideoBoxApplication.initAppForSDK (VideoBoxApplication.java)
com.zipow.videobox.VideoBoxApplication.onSDKCreated (VideoBoxApplication.java)
com.zipow.videobox.VideoBoxApplication.initializeForSDK (VideoBoxApplication.java)
us.zoom.sdk.ZoomSDK.initialize (ZoomSDK.java)
ch.milosz.reactnative.RNZoomUsModule$2.run (RNZoomUsModule.java)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:264)
android.app.ActivityThread.main (ActivityThread.java:8282)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:632)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1049)

```

**Comment by pmogollons** [comment] 2022-02-01 15:23
This might be caused by zoom sdk not being compatible with android 12 yet. Possible duplicate of #180.

Please check if this error only happens to users with android 12 devices.

**Comment by bhavesh0206s** [comment] 2022-02-01 16:59
This is happening on android 11. Our targetSdkVersion is 30

**Comment by pmogollons** [comment] 2022-02-01 20:46
The tagetSdkVersion is actually not relevant to the issue. Is the version of the OS running on the device you are having this issue.

If you are running android 11 in your device, could you please help with a reproduction repo.

**Comment by mieszko4** [comment] 2022-05-16 07:25
I've build my Android 11 with new 6.9.0 correctly so you may try with that now.

**Closed by mieszko4** 2022-05-16 07:25 UTC
