### ISSUE TITLE
app stuck at lunch screen IOS

### ISSUE THREAD

**Issue by sanjaymj12345** [mieszko4/react-native-zoom-us#181] opened 2022-01-17 14:24 UTC
**error in xcode** 
dyld: Library not loaded: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation
  Referenced from: /var/containers/Bundle/Application/8B6DCBDC-562D-42BD-80BF-1D5438D4DCC3/hotstep.app/hotstep
  Reason: image not found

**xcode version**
Version 13.2.1 (13C100)

**device os version**
Iphone 6 plus
software iOS 12.5.5

**Comment by mieszko4** [comment] 2022-02-02 10:09
Perhaps you could try with new version v6.7.0

**Comment by mieszko4** [comment] 2022-05-16 07:41
Could not reproduce, I tried with example app https://github.com/mieszko4/react-native-zoom-us-test. Closing it. Feel free to reopen if it happens to you again. Providing more context would be useful :)

**Closed by mieszko4** 2022-05-16 07:41 UTC

**Comment by cloudy-ninja** [comment] 2023-05-22 21:33
@mieszko4 This issue is happening on the M2 processor, but it's working well with the intel process. Do you have any insight on this?

**Comment by mieszko4** [comment] 2023-07-10 09:12
I recently upgraded Zoom SDK for iOS so maybe 6.17.0 will help
