### ISSUE TITLE
[deprecation] MeetingActivity in us.zoom.sdk has been deprecated

### ISSUE THREAD

**Issue by shafqatbari** [mieszko4/react-native-zoom-us#261] opened 2023-02-13 07:47 UTC
I am using 
 "react-native-zoom-us": "^6.9.0",

`176 actionable tasks: 7 executed, 169 up-to-date
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsActivity.java:4: warning: [deprecation] MeetingActivity in us.zoom.sdk has been deprecated
import us.zoom.sdk.MeetingActivity;
                  ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:76: error: RNZoomUsModule is not abstract and does not override abstract method onLocalRecordingPrivilegeRequested(IRequestLocalRecordingPrivilegeHandler) in InMeetingServiceListener
public class RNZoomUsModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, InMeetingServiceListener, MeetingServiceListener, InMeetingShareController.InMeetingShareListener, LifecycleEventListener {
       ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:1122: warning: [deprecation] onShareActiveUser(long) in InMeetingShareListener has been deprecated
  public void onShareActiveUser(long userId) {
              ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:209: warning: [deprecation] Integer(int) in Integer has been deprecated
      videoViews.add(new Integer(tagId));
                     ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java:219: warning: [deprecation] Integer(int) in Integer has been deprecated
      videoViews.remove(new Integer(tagId));
                        ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsVideoView.java:61: warning: [deprecation] Long(long) in Long has been deprecated
      users.remove(new Long(inMeetingService.getMyUserID()));
                   ^
/Volumes/ReporteqProjects/SalusHealth_MobileApp/node_modules/react-native-zoom-us/android/src/main/java/ch/milosz/reactnative/RNZoomUsActivity.java:6: warning: [deprecation] MeetingActivity in us.zoom.sdk has been deprecated
public class RNZoomUsActivity extends MeetingActivity {
                                      ^
1 error
6 warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-zoom-us:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/activity_media_player.xml:7: AAPT: error: attribute controller_layout_id (aka com.salushealth:controller_layout_id) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_video_player.xml:8: AAPT: error: attribute controller_layout_id (aka com.salushealth:controller_layout_id) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_video_player.xml:8: AAPT: error: attribute show_timeout (aka com.salushealth:show_timeout) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_video_player.xml:8: AAPT: error: attribute hide_on_touch (aka com.salushealth:hide_on_touch) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_video_player.xml:8: AAPT: error: attribute shutter_background_color (aka com.salushealth:shutter_background_color) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_video_player.xml:8: AAPT: error: attribute resize_mode (aka com.salushealth:resize_mode) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_videomail_player.xml:8: AAPT: error: attribute hide_on_touch (aka com.salushealth:hide_on_touch) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_videomail_player.xml:8: AAPT: error: attribute show_timeout (aka com.salushealth:show_timeout) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/fragment_sip_videomail_player.xml:8: AAPT: error: attribute controller_layout_id (aka com.salushealth:controller_layout_id) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/media_player_playback_control.xml:33: AAPT: error: resource id/exo_rew (aka com.salushealth:id/exo_rew) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/media_player_playback_control.xml:33: AAPT: error: resource style/ExoMediaButton.Rewind (aka com.salushealth:style/ExoMediaButton.Rewind) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/media_player_playback_control.xml:37: AAPT: error: resource id/exo_play (aka com.salushealth:id/exo_play) not found.
         
     ERROR:/Users/shafqatbari/.gradle/caches/transforms-3/e9b9775f38bad343aa040e35c99099c7/transformed/jetified-mobilertc/res/layout/media_player_playback_control.xml:37: AAPT: error: resource style/ExoMediaButton.Play (aka com.salushealth:style/ExoMediaButton.Play) not found.`

**Comment by mieszko4** [comment] 2023-02-14 06:41
Please try with newest `6.16.5`. Also see [test app](https://github.com/mieszko4/react-native-zoom-us-test).

**Comment by mieszko4** [comment] 2023-02-14 07:23
Duplicate of https://github.com/mieszko4/react-native-zoom-us/issues/260

**Closed by mieszko4** 2023-02-14 07:23 UTC
