### ISSUE TITLE
[Android] Failed to Join Zoom Meeting

### ISSUE THREAD

**Issue by vitorizkiimanda** [mieszko4/react-native-zoom-us#173] opened 2021-12-13 15:40 UTC
Just updated this library from 5.9.0 -> 6.6.1 

IOS -> smoothly updated

Android -> error when joining zoom meeting (image below )
- already follow readme android installation
- android/app/build.gradle
`packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
		pickFirst '**/*.so'
    }`
- and mainApplication.java

![image](https://user-images.githubusercontent.com/28048320/145841748-959440a8-3530-4131-a16f-7ccb70e6bc19.png)

**Comment by mieszko4** [comment] 2021-12-13 17:20
:thinking: From what I can see your build has passed through, right?
My guess it that there is some conflict with other native libs that you use in your project  or the problem is with the device or maybe you need to update gradle, sdk...

Could you try to run it on emulator?

Also note that this is a working demo version https://github.com/mieszko4/react-native-zoom-us-test so you may try to run that first.

**Comment by vitorizkiimanda** [comment] 2021-12-13 20:17
correct, the build has been passed.. 

okay gonna check the example repo first and skim the code. Maybe there is some changes in android native config from 5.9.0

**Comment by vitorizkiimanda** [comment] 2021-12-13 20:22
just found one different config code. flat dir in android/build.gradle has been removed. Sadly the problem still occured.
And more sadly, couldnt test it on android emulator because im using M1 chip macbook 😢 

gonna try to run example apps first though

**Comment by vitorizkiimanda** [comment] 2021-12-13 21:53
just tried example apps. it works on my phone..  
im a bit confuse here, because in 5.9.0 nothings wrong

**Comment by vitorizkiimanda** [comment] 2021-12-13 22:06
if my packaginOptions like this , its okay right?
`packagingOptions {
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
		pickFirst '**/*.so'
    }`

**Comment by mieszko4** [comment] 2021-12-15 07:50
> if my packaginOptions like this , its okay right?
> `packagingOptions { pickFirst 'lib/arm64-v8a/libc++_shared.so' pickFirst 'lib/x86/libc++_shared.so' pickFirst 'lib/x86_64/libc++_shared.so' pickFirst 'lib/armeabi-v7a/libc++_shared.so' pickFirst '**/*.so' }`

In demo app there is no `pickFirst '**/*.so'`

You've followed these steps, right? https://github.com/mieszko4/react-native-zoom-us/blob/master/docs/UPGRADING.md#600-jitpack

Also Here is the diff from `5.9.0` to `6.6.1` for the demo app  - https://github.com/mieszko4/react-native-zoom-us-test/compare/bfb4092278945e5a9ba5206919dad7487a44980c...master#diff-9526ccfd1d1813ed49c39f8c54dbeb512607376a007d824b905bc8b4e4d202d9R137-R143
You can check there which `packagingOptions` were applied.

If `5.9.0` was working for you, my other thought is that some other native lib may start conflicting with newer zoom us sdk. Maybe you could upgrade the lib step by step and see at which point it starts to crash.

**Comment by vitorizkiimanda** [comment] 2021-12-15 08:49
just checkin https://github.com/mieszko4/react-native-zoom-us/blob/master/docs/UPGRADING.md#600-jitpack

my apps use customized-exoplayer for video playback. thats might be the issue. thanks for the info
gonna debug further

**Comment by vitorizkiimanda** [comment] 2022-02-02 01:21
> @vitorizkiimanda were you able to fix this issue?

i havent able to fix it @pmogollons   , in the meanthime i choose to downgrade the version first ( or cancel to update to latest version )

do you have any solution?

**Comment by pmogollons** [comment] 2022-03-15 12:31
Try using the latest version, apart from that not much. Havent seen this kind of issue before. Maybe you can create a reproduction repo.

**Comment by mieszko4** [comment] 2022-03-15 20:43
I will close it. Feel free to reopen.

**Closed by mieszko4** 2022-03-15 20:43 UTC
